# Site settings
title: Secret Escapes

description: >
  We’re all in this together. Staying indoors is hard, so to make things a little easier, we’ve handpicked some of our favourite apps and activities that can help you pass the time - your daily dose of escapism. We also know that you’re still dreaming about travel, and we don’t want that to stop. So, we’ll continue to inspire you for a day when we can once again get out and explore. 

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/daily-escapes" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/daily-escapes/_assets/img"
css:     "/uk/2020/daily-escapes/_assets/css"
js:      "/uk/2020/daily-escapes/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed