


###################################################################################################
# CREATIVITY
###################################################################################################

- id: photobox
  category: creativity
  incentive: "Get 50% off everything with our exclusive discount code: CANTWAITTOESCAPE"
  terms: This offer entitles you to 50% off across the site with no minimum spend. Promotion does not apply to Delivery Charges, Gift Vouchers and Product Credits from Credit Sale. Cannot be used in conjunction with other discount codes and offers. Any monetary credits will be applied before any promotional discounts. All standard terms & conditions apply.
  product:
    name: Photobox
    tagline: Bring your photos to life
    color: "#007376"
    link: https://www.photobox.co.uk/
    cta-text: Create now
    features:
      - id: feature1
        title: Feature
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      - id: feature2
        title: Feature
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      - id: feature3
        title: Feature
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.



###################################################################################################
# GIFTING
###################################################################################################

- id: appleyard
  category: gifting
  incentive: Get 20% off flowers, the perfect gift for any occasion!
  product:
    name: Appleyard Flowers
    tagline: Send the perfect gift
    link: https://www.appleyardflowers.com/
    color: "#C88FA2"
    cta-text: Find out more
    features:
      - id: feature1
        title: Luxury but affordable gifts
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      - id: feature2
        title: Hampers
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      - id: feature3
        title: Contactless delivery
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.



###################################################################################################
# FITNESS
###################################################################################################

- id: gymondo
  category: fitness
  incentive: 30% discount for your first month of Gymondo
  product:
    name: Gymondo
    tagline: Get Fit & Happy at Home
    link: https://www.gymondo.com/en/
    color: "#FD7E65"
    features:
      - id: feature1
        title: Feature
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      - id: feature2
        title: Feature
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      - id: feature3
        title: Feature
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.



###################################################################################################
# ENTERTAINMENT
###################################################################################################

- id: audible
  category: entertainment
  incentive: Get 50% off membership for 3 months
  product:
    name: Audible
    tagline: Stories that speak to you
    link: https://www.audible.co.uk/ep/399_membership
    color: "#f89a1d"
    features:
      - id: feature1
        title: Feature
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      - id: feature2
        title: Feature
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.
      - id: feature3
        title: Feature
        content: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.





