


###################################################################################################
# CREATIVITY
###################################################################################################

- id: photobox
  category: creativity
  incentive: "Save up to 50% in the spring sale event as well as an extra 10% with our code: CANTWAITTOESCAPE"
  terms: This offer entitles you to an additional 10% off across the site with no minimum spend. Promotion does not apply to Delivery Charges, Gift Vouchers and Product Credits from Credit Sale. May be used in conjunction with one other eligible discount offer. Expires 30 April 2020. All standard terms & conditions apply.
  product:
    name: Photobox
    tagline: Bring your photos to life
    color: "#007376"
    link: https://www.photobox.co.uk/
    cta-text: Create now
    features:
      - id: feature1
        title: Reflect
        content: While we hope and plan for future holidays, it’s also important to cherish the trips we’ve had with the ones we love. Why not take this time to reminisce about your previous travels and create a beautiful memory book to cherish. Surprise your friends by showing them when you next meet up.
      - id: feature2
        title: Create
        content: So why not snuggle up this week with a photo project? Create beautiful keepsakes of your favourite trips which can be delivered right to the letterbox of you or a loved one.
      - id: feature3
        title: Showstoppers
        content: Got a showstopping wildlife photograph or some sensational scenery that deserves to be shown off? Showcase your travels in art at home or send a gift to a loved one.

- id: touchnote
  category: creativity
  incentive: "Enjoy four photocards for free when you use our special code: ESCAPE"
  terms:
  product:
    name: TouchNote
    tagline: Stay in touch with those you love
    color: "#3CAEBB"
    link: https://touchnote.onelink.me/3205415180?pid=Partnerships&c=TouchNote-Secret%20Escapes_ESCAPE&af_dp=tn%3A%2F%2Fpromocode%2FESCAPE&af_web_dp=https%3A%2F%2Fapp.touchnote.com%2Fa%2FPROMO%2FESCAPE
    cta-text: Download now
    features:
      - id: feature1
        title: Create
        content: With free worldwide delivery, it doesn’t matter who you want to get in touch with. Connect with loved ones with personalised photo cards sent straight from your phone. All it takes is your favourite pics, a heartfelt message and in a few taps, it’ll be on its way. Easy.
      - id: feature2
        title: Connect
        content: Feel good with TouchNote. Did you know that 3 in 4 TouchNote members believe it has strengthened their relationships? Spread some positive vibes and show someone you’re thinking of them with a unique, beautiful card.
      - id: feature3
        title: Cherish
        content: Printed to the highest quality, TouchNote cards are made to last. With 95% of members feeling happier when surrounded by photos of their loved ones, it’s a good thing their cards stick around for so long.



###################################################################################################
# GIFTING
###################################################################################################

- id: appleyard
  category: gifting
  incentive: "Enjoy 20% off all bouquets with our special discount code: SECRET20"
  product:
    name: Appleyard Flowers
    tagline: Send the perfect gift
    link: https://www.appleyardflowers.com/
    color: "#C88FA2"
    cta-text: Find out more
    features:
      - id: feature1
        title: Life’s little luxuries
        content: In these uncertain times, we are all in need of a little pick-me-up. Flowers are the perfect way to put a smile on someone’s face. Appleyard deliver a range of luxury and affordable gifts, including hampers, to your homes. Ideal for a birthday, anniversary, or a special weekend treat.
      - id: feature2
        title: Delivering safely
        content: Appleyard deliveries are now contact-free. Couriers will leave your delivery in a safe place, to keep within a safe distance. Our letterbox flowers will be delivered through the letterbox as usual. You’ll receive prompt delivery updates to let you know when your parcel has arrived.
      - id: feature3
        title: Giving back
        content: Appleyard are fundraising in aid of NHS charities which support NHS staff and volunteers in various ways. When you checkout, there will be an option to add a small donation to your purchase. Appleyard will then match all donations.

- id: espa
  category: gifting
  passive: true
  incentive: Re-create the spa experience at home with ESPA
  product:
    name: ESPA
    tagline: Escape at home
    link: https://www.awin1.com/cread.php?awinmid=11310&awinaffid=698587&ued=https%3A%2F%2Fwww.espaskincare.com%2F
    color: "#625e5d"
    features:
      - id: feature1
        title: Focus on wellbeing
        content: ESPA are guided by a holistic philosophy, caring for your whole wellbeing, focusing on creating natural skincare products that could deliver both instant benefits and also work beneath the skins surface to protect the long term health and beauty of the skin.
      - id: feature2
        title: Escape at home
        content: Re-create the spa experience at home with ESPA’s selection of beautifully formulated, natural products designed to restore your skin, body and mind. Investing in our wellbeing, now more than ever, is vital, and what better way to start than with your skin and a good hand cream?
      - id: feature3
        title: Radiant skin
        content: Taking care of our skin makes us look and feel at our best. Using ESPA’s range of quality natural products as part of your daily skincare routine will soften, repair and revitalise your skin, giving you a healthy glow, and a boost when you need it most.



###################################################################################################
# FITNESS
###################################################################################################

- id: gymondo
  category: fitness
  incentive: 25% discount on your first Gymondo membership package
  product:
    name: Gymondo
    tagline: Get fit & happy at home
    link: https://www.gymondo.com/en/checkout/?voucher=3speun6v&utm_source=partner&utm_medium=NL&utm_campaign=SecretEscapesUK
    color: "#FD7E65"
    features:
      - id: feature1
        title: Get active
        content: While we’re stuck at home it’s really important to move our bodies every day. With Gymondo, you can enjoy effective home workouts with motivational coaches to help make exercising become a fun and enjoyable habit - anywhere, anytime.
      - id: feature2
        title: Fun and diverse workouts
        content: Find the workout that’s best for you and your body, with Gymondo’s diverse range of fitness programs. From yoga to HIIT, there’s over 200 motivating workouts, and over 800 recipes offering full flexibility that fits you and your lifestyle.
      - id: feature3
        title: Healthy & nutritious meals
        content: Nutrition is just as important as an active lifestyle. Choose from select recipes based on your preference and dietary requirements. Gymondo supports you with their recipes and the Gymondo nutrition plan to eat healthy and reach your fitness goals faster.



###################################################################################################
# READING
###################################################################################################

- id: ng-traveller
  category: reading
  incentive: Enjoy three issues of Nat Geo Traveller for only £1
  product:
    name: Nat Geo Traveller
    tagline: Perfect for travel enthusiasts the world over
    link: https://natgeotraveller.imbmsubscriptions.com/ngtescape/
    cta-text: Order now
    color: "#FCCC3E"
    low-contrast: true
    features:
      - id: feature1
        title: Inspiring
        content: With compelling storytelling, wish-you-were-there photography and insightful, reader-friendly information - National Geographic Traveller is perfect for travel enthusiasts the world over. This magazine is not only full of passion for experiencing the world, but it also champions sustainable travel and celebrates journeys about place and culture.
      - id: feature2
        title: The perfect gift
        content: National Geographic Traveller is a thoughtful gift idea for your friends and family who are keen explorers. Jam-packed with fascinating storytelling and wish-you-were-there photography, you'll definitely satisfy their itch to travel
      - id: feature3
        title: Award winner
        content: Named 'Best Consumer Travel Magazine' at the British Travel Awards 2019, National Geographic Traveller UK is ready to help prepare you for your next adventure.



###################################################################################################
# MINDFULNESS
###################################################################################################

- id: lsw-mind-cards
  category: mindfulness
  incentive: "Free guided meditation recording with every purchase using code: SECRETESCAPES"
  product:
    name: LSW Mind Cards
    tagline: Boost your wellbeing and your mood with LSW Mind Cards
    link: https://lswmindcards.com/
    color: "#96acc9"
    features:
      - id: feature1
        title: Cards with a purpose
        content: LSW Mind Cards are a pack of 45 individually designed cards each with a tool or task to help you increase your wellbeing, boost your mood and help you move towards a more fulfilled life.
      - id: feature2
        title: Creating positive habits
        content: By introducing positive habits into your everyday, Mind Cards will give you the power to create the healthiest and happiest life for you.
      - id: feature3
        title: Take action
        content: Each day select a card at random and take the action stated on the card. Building the habit of making at least one positive choice each day will help you lead a more fulfilling and happier life.



